//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMiCay
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QuanLyQuanMiCayEntities : DbContext
    {
        public QuanLyQuanMiCayEntities()
            : base("name=QuanLyQuanMiCayEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<KhachHang> KhachHang { get; set; }
        public virtual DbSet<TaiKhoanKhach> TaiKhoanKhach { get; set; }
        public virtual DbSet<NhanVien> NhanVien { get; set; }
        public virtual DbSet<TaiKhoanNhanVien> TaiKhoanNhanVien { get; set; }
        public virtual DbSet<VaiTro> VaiTro { get; set; }
    
        public virtual int sp_InsertKhachHang(string tenKH, string sDT, Nullable<System.DateTime> ngaySinh, string diaChi, string gioiTinh, string tenTaiKhoanKhach, string matKhauKhach)
        {
            var tenKHParameter = tenKH != null ?
                new ObjectParameter("TenKH", tenKH) :
                new ObjectParameter("TenKH", typeof(string));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(System.DateTime));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var gioiTinhParameter = gioiTinh != null ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(string));
    
            var tenTaiKhoanKhachParameter = tenTaiKhoanKhach != null ?
                new ObjectParameter("TenTaiKhoanKhach", tenTaiKhoanKhach) :
                new ObjectParameter("TenTaiKhoanKhach", typeof(string));
    
            var matKhauKhachParameter = matKhauKhach != null ?
                new ObjectParameter("MatKhauKhach", matKhauKhach) :
                new ObjectParameter("MatKhauKhach", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertKhachHang", tenKHParameter, sDTParameter, ngaySinhParameter, diaChiParameter, gioiTinhParameter, tenTaiKhoanKhachParameter, matKhauKhachParameter);
        }
    
        public virtual int sp_InsertNhanVien(string tenNV, string sDTNV, Nullable<System.DateTime> ngaySinh, string diaChi, string gioiTinh, string tenTaiKhoanNV, string matKhau)
        {
            var tenNVParameter = tenNV != null ?
                new ObjectParameter("TenNV", tenNV) :
                new ObjectParameter("TenNV", typeof(string));
    
            var sDTNVParameter = sDTNV != null ?
                new ObjectParameter("SDTNV", sDTNV) :
                new ObjectParameter("SDTNV", typeof(string));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(System.DateTime));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var gioiTinhParameter = gioiTinh != null ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(string));
    
            var tenTaiKhoanNVParameter = tenTaiKhoanNV != null ?
                new ObjectParameter("TenTaiKhoanNV", tenTaiKhoanNV) :
                new ObjectParameter("TenTaiKhoanNV", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertNhanVien", tenNVParameter, sDTNVParameter, ngaySinhParameter, diaChiParameter, gioiTinhParameter, tenTaiKhoanNVParameter, matKhauParameter);
        }
    }
}
